### ISSUE TITLE
Link to pretrained models broken

### ISSUE THREAD

**Issue by imisra** [MehdiNoroozi/JigsawPuzzleSolver#7]
Hi,

The pretrained models link (http://www.cvg.unibe.ch/research/JigsawPuzzleSolver.html) is down.

**Comment by TemplatePage** [comment]
Hi Ishan,

Thanks for bringing this up.It has been fixed now. You can also find newer pre-trained models with higher performance here:
http://www.cvg.unibe.ch/media/project/noroozi/knowledge_transfer.htm

**Comment by MehdiNoroozi** [comment]
Hi,

Thanks for bringing this up. It has been fixed now. You can also find newer  pre-trained models with higher performance here:
http://www.cvg.unibe.ch/media/project/noroozi/knowledge_transfer.htm
